### ISSUE TITLE
Backstage2 keep session

### ISSUE THREAD

**Issue by GH0STL1N3R** [wlox/wlox#101]
Hi,

I am having troubles with Backstage2. 

It's succesfully installed however, once logged is, it does not keep the session and therefore doesn't save data. 

I have tried clearing cookies and cache, using in different browser and even commented: lib/common.php to //session_regenerate_id();

Nothing works so far. 

Do you have any suggestions?

**Comment by GH0STL1N3R** [comment]
Solved by using a different(older) php version

**Comment by directoryio** [comment]
what your php version ?
