### ISSUE TITLE
Cannot get frontend to load

### ISSUE THREAD

**Issue by htskltd91989** [wlox/wlox#104]
Trying to access front end throws 500 internal server error.

I am unsure if my frontend.cfg is set correctly - I have it set for passwordless ssh access to the server that the appropriate files reside on. The passwordless ssh is confirmed to be working, but i am unsure if it is interpreting the command the way I want it to - does it HAVE to be a url in the .cfg file?

**Comment by exploshot** [comment]
how did you fixed that issue?

**Comment by seminara** [comment]
I have the same issue.......the backend is working fine but I get a server500 on the front end...any one know how to solve?
