### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by ghost** [wlox/wlox#116]

**Comment by otaviobps** [comment]
Hi, I tried to visit your website but it keeps loading

**Comment by otaviobonder** [comment]
Hi, are you available to develop a new exchange?

**Comment by mxo2** [comment]
we are developing new excahnge.contact sam@mxo2.com

**Comment by BitifySouthAfrica** [comment]
Yes of course I am available to setup another exchange, please feel free to contact us via info@bitify.co.za
