### ISSUE TITLE
[backstage2] cfg object errors on startup

### ISSUE THREAD

**Issue by sugruedes** [wlox/wlox#38]
the cfg object has only 4 properties from cfg.php, but ```/wlox/backstage2/shared2/dblib.php``` line 28 is looking for  ```object::$dont_select_db``` among others...

**Comment by mbassan** [comment]
Although WLOX itself has pretty clean code, we can't say the same for backstage2. At this point, we recommend turning off PHP notices and strict. You can try setting error_reporting(E_ALL && ~E_NOTICE && ~E_STRICT) in the cfg.php file.

We are pending a serious update for backstage2. But it functions for the required purposes at this point. The code is just a bit messy at this point.

**Comment by mbassan** [comment]
By the way, you can contact us at support.wlox on Skype if you need some more responsive assistance.

**Comment by sugruedes** [comment]
hi mbasson, thanks for the update. i was trying to get it up and running but have error_reporting 'on' :-(

I will relax error reporting and let you know.  Good luck with it, I will feedback and help what i can.

**Comment by sugruedes** [comment]
Ok, great! That worked. Thanks!

**Comment by mbassan** [comment]
Glad I can help. Let me know if you have any more questions.

**Comment by rafaelsaru** [comment]
Hi mbassan.. i cant stay logged in backstage.. everytime its goes out.. do you know how to fix?

**Comment by bitsexchange** [comment]
Mbassan could I pay for a professional setup?

**Comment by mbassan** [comment]
You definitely can. Please contact us on Skype at support.wlox. Best
regards.

On Mon, Mar 21, 2016 at 11:59 AM, bitsexchange notifications@github.com
wrote:

> Mbassan could I pay for a professional setup?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/wlox/wlox/issues/38#issuecomment-199379635

## 

Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan
