### ISSUE TITLE
Application timezone

### ISSUE THREAD

**Issue by albabosh** [wlox/wlox#39]
What should be there in the Application Timezone field ? Nothing works. 

Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /home/lwloqtss/lib/common.php:28

**Comment by mbassan** [comment]
Actually, that error means that wlox-frontend is not connecting to wlox-api at all. Did you already get backstage2 working? You need to fill in the necessary values in backstage2 under 'status'->'app configuration' to tell the frontend where to find wlox-api and wlox-auth instances.

If you have already done that, try setting:
```error_reporting(7);
ini_set('display_errors',1);```

in the wlox-frontend/cfg/cfg.php file to at least see what PHP errors are ocurring.

**Comment by albabosh** [comment]
I got backstage working fine, I have edited the frontend config, but I dont know how to tell the frontend where to find wlox-api & wlox-auth as they are on another servers. Could you tell me ?

**Comment by mbassan** [comment]
You need to follow the instructions in the readme.md file: Rename wlox-frontend/cfg/cfg.example.php to cfg.php, then define the following variables:
```
$CFG->api_url = 'http://my-ip-or-server/api.php';
$CFG->auth_login_url = 'http://my-ip-or-server/htdocs/login.php';
$CFG->auth_verify_token_url = 'http://my-ip-or-server/htdocs/verify_token.php';

**Comment by mbassan** [comment]
Please contact me on Skype at support.wlox to ask these kinds of questions.
