### ISSUE TITLE
Error Install Backstage2

### ISSUE THREAD

**Issue by thecc** [wlox/wlox#43]
Hello,

can help me because this error occurs:
Strict Standards: Non-static method Ops :: getPageTitle () should not be called statically, assuming $ this from incompatible context in /home/axcoins/public_html/patak/shared2/Form.php on line 2660
This is an example to access with admin admin, the error becomes many lines.

**Comment by mbassan** [comment]
Put this in your config.cfg file in backstage :
error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT);

**Comment by mbassan** [comment]
Sorry, I meant to put it in cfg.php.
