### ISSUE TITLE
Setup Details

### ISSUE THREAD

**Issue by geopayme** [wlox/wlox#44]
Can someone  provide better instructions to setup a development platform?

does the bitcoind server need to run the same machine as the wlox code? 
How many server does someone need to setup the  production platform?

Can other coins be added to the platform like DOGE and LTC?

Thanks

**Comment by geopayme** [comment]
I followed your instructions as you specified and this the result... 

print = $_REQUEST['print']; $CFG->url = ($_REQUEST['current_url'] != 'index.php') ? ereg_replace("[^a-zA-Z_\-]", "",$_REQUEST['current_url']) : ''; $CFG->action = ereg_replace("[^a-zA-Z_\-]", "",$_REQUEST['action']); $CFG->bypass = ($_REQUEST['bypass'] || $CFG->print); $CFG->is_tab = (!$CFG->url) ? 1 : $_REQUEST['is_tab']; $CFG->id = ereg_replace("[^0-9]", "",$_REQUEST['id']); $CFG->target_elem = ereg_replace("[^a-zA-Z_\-]", "",$_REQUEST['target_elem']); $CFG->in_popup = ($CFG->target_elem == 'edit_box' || $CFG->target_elem == 'message_box' || $CFG->target_elem == 'attributes box'); $_SESSION['last_query'] = $_SESSION['this_query']; $_SESSION['this_query'] = 'index.php?'.http_build_query((is_array($_POST)) ? $_POST : $_GET); date_default_timezone_set($CFG->default_timezone); String::magicQuotesOff(); if ($CFG->locale) { setlocale(LC_ALL,$CFG->locale); } if (!$CFG->bypass || ($CFG->bypass && $CFG->print)) { $header = new Header(); $header->metaAuthor(); $header->metaDesc(); $header->metaKeywords(); $header->cssFile('css/colorpicker.css'); $header->cssFile('css/reset.css'); $header->cssFile('css/'.$CFG->skin.'/default.css','all'); $header->cssFile('css/'.$CFG->skin.'/default_ie6.css','all','IE 6'); $header->cssFile('css/'.$CFG->skin.'/default_ie7.css','all','IE 7'); $header->cssFile('css/'.$CFG->skin.'/default_ie8.css','all','IE 8'); $header->jsFile('js/jquery-1.4.2.min.js'); $header->jsFile('js/jquery-ui-1.8.5.custom.min.js'); $header->jsFile('js/ajax.js'); $header->jsFile('js/calendar.js'); $header->jsFile('js/colorpicker.js'); $header->jsFile('js/comments.js'); $header->jsFile('js/form.js'); $header->jsFile('js/file_manager.js'); $header->jsFile('js/flow_chart.js'); $header->jsFile('js/gallery.js'); $header->jsFile('js/grid.js'); $header->jsFile('js/multi_list.js'); $header->jsFile('js/popups.js'); $header->jsFile('js/page_maker.js'); $header->jsFile('js/permissions.js'); $header->jsFile('js/swfupload.js'); $header->jsFile('js/jquery.swfupload.js'); $header->jsFile('ckeditor/ckeditor.js'); $header->jsFile('js/Ops.js'); $header->js('CKEDITOR.dtd.$removeEmpty[\'span\'] = false;'); $header->display(); $header->getJsGlobals(); } if ($_REQUEST['authy_form']) { $token1 = ereg_replace("[^0-9]", "",$_REQUEST['authy_form']['token']); if (!($token1 > 0)) Errors::add('Invalid token.'); if (!is_array(Errors::$errors)) { $authy_id = User::$info['authy_id']; $response = shell_exec('curl "https://api.authy.com/protected/json/verify/'.$token1.'/'.User::$info['authy_id'].'?api_key='.$CFG->authy_api_key.'"'); $response1 = json_decode($response,true); if (!$response || !is_array($response1)) Errors::merge('Authy communication error.'); if (!empty($response1['errors']) || $response1['success'] === false || $response1['success'] === 'false') Errors::merge($response1['errors']); if (!is_array(Errors::$errors)) { $_SESSION['token_verified'] = 1; Errors::$errors = false; } } } if (User::isLoggedIn() && !(User::$info['verified_authy'] == 'Y' && !($_SESSION['token_verified'] > 0))) { $CFG->user_id = User::$info['id']; $CFG->group_id = User::$info['f_id']; if (!$CFG->bypass || ($CFG->url == 'edit_page' && !$_REQUEST['tab_bypass'])) { include_once 'includes/popups.php'; ?>


Any thoughts as to why?

**Comment by mbassan** [comment]
Hi geopayme,

The bitcoind server should run on the same server as the wlox-dev package. For a production environment, you should probably have a minimum of three servers distributed in the following way:

Server 1: wlox-frontend
Server 2: wlox-api, wlox-cron, bitcoind, backstage2
Server 3: wlox-auth

I would, however, recommend de-coupling wlox-api into it's own server for extra security, as well as placing an IP restriction on backstage2 access to allow only from a couple physical locations.

About the DOGE and LTC, you can use them, but at this time we only support one cryptocurrency at a time. You could technically run multiple instances of WLOX integrated into one website, however. It just wouldn't allow trading BTC to LTC for example. You can also modify the WLOX code any way you want if you would like to develop a new feature for multiple cryptocurrencies.

Last of all, the strange result you got in your second comment are because you need to enable **short PHP tags** on all your PHP servers.

**Comment by geopayme** [comment]
Thanks for the details.. wlox is an interesting product....

**Comment by mbassan** [comment]
Thanks for the positive feedback. Feel free to contact us on Skype at support.wlox if you have any more tech questions.

**Comment by Freefromchainz** [comment]
mbassan I am having a similar issue, is it really imperative that i use 3 servers to git the exhange to work. also I am using Ubuntu 14 on digital Ocean cloud server. and everything i put in http://mysite.com.backstage2 it says no site available.

**Comment by mbassan** [comment]
As it says in both my comment and in the manual, multiple servers are for a **production environment**. For a testing environment, one server is fine.
