### ISSUE TITLE
Backstage2 Installation troubles

### ISSUE THREAD

**Issue by ILoveCrypto** [wlox/wlox#46]
I followed all the oultined steps in the instructions. Moved backstage2 to /var/www/html/backstage2/. Configured the appropiate database settings etc. Installed and enabled the mcrypt module. Added short_open_tag=On to php.ini. But when I go to myurl.com/backstage2/ It shows,
![backstage2-error](https://cloud.githubusercontent.com/assets/12470025/7665137/e4b6d260-fb77-11e4-92a1-bbade7a10a91.png)

What steps can I take to fix this?

**Comment by ILoveCrypto** [comment]
Installed php5-gd, cant find php5-pcre. All other modules are installed. Error still remains.

**Comment by mbassan** [comment]
Hello ILoveCrypto,

Just add the following lines to your backstage2/cfg.php:

error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT) ;

Best,

WLOX Support

**Comment by ILoveCrypto** [comment]
Mbassan, I added the suggested line and the error still remains. I would really appreciate your help. I sent you a Skype message..

**Comment by mbassan** [comment]
Did you put it inside the <?  ?> tags? It's PHP code.

Sorry, just got into the office now. I will add you.

**Comment by mbassan** [comment]
Actually, I just realized, you need to enable **short php tags**.

**Comment by minerlab** [comment]
How was it resolved? I have the same problem too
