### ISSUE TITLE
Error in backstage2

### ISSUE THREAD

**Issue by imatsu** [wlox/wlox#48]
just after install backstage2, backstage2 force logout user for every click menu, and redirect to /index.php?current_url=app-configuration or another click menu

**Comment by mbassan** [comment]
Hola Hector,

Me estas diciendo que backstage pierde la sesión del usuario cada vez que
cargas la página?

Abre el archivo backstage2/lib/common.php, busca donde dice
session_regenerate_id() y comentalo poniendo // por delante.

Me avisas si funciona.

Atentamente,

Soporte de WLOX

**Comment by imatsu** [comment]
Saludos, 

Muchas gracias, ya funciona, estaba pensando que era un problema de configuración del webserver.

**Comment by mbassan** [comment]
Perfecto. Puede hacer lo mismo para wlox-frontend también si tiene algún
problema.

Saludos.

**Comment by imatsu** [comment]
Este procedimiento también debería hacerlo en producción?

**Comment by mbassan** [comment]
Probablemente no. La verdad es que no he investigado la razón que algunas
personas tienen problemas regenerando la sesión.

**Comment by imatsu** [comment]
Saludos.

mbassan, estoy tratando de configurar el servidor con nginx+php5-fpm, pero el frontend al seleccionar el idioma cambia la url del la siguiente manera

para inglés index.php
para español /es/index.php

los enlaces para inglés funcionan adecuadamente, sin embargo para español me retorna un 404, me pregunto si existe alguna configuración extra que deba añadir en el nginx ya que en el servidor web apache funcionaba normalmente.

**Comment by imatsu** [comment]
Saludos, 

Disculpa la molestia, estoy configurando el servidor web para la api y auth por el puerto 443 con certificado SSL, y el frontend me está dando el siguiente error:

PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /var/www/html/xemcoins/wlox/frontend/lib/common.php:68

Esto no me ocurre si lo pongo a funcionar en el puerto 80, quisiera saber que debo hacer para mantener la api conectada por el puerto 443.

Muchas gracias por tu respuesta

**Comment by mbassan** [comment]
Buenas Héctor,

Los directivos de rewrite se encuentran en el archivo  .htaccess de
frontend/htdocs. No tengo casi experiencia utilizando Nginx y no se como se
podría configurar para utilizar los directivos.

Como un fix temporal podrías abrir frontend/lib/Lang.php ::url() y
manualmente enviar el URL original en inglés.

Me avisas si te funciona.

**Comment by mbassan** [comment]
El error de DateTimeZone ocurre cuando el frontend no encuentra el servidor
API. No estoy seguro porqué cambiar de puerto causa eso. Quizás el cfg de
frontend hace falta cambiar los urls de http a https? No creo que se
especifica el puerto en ese caso.

**Comment by imatsu** [comment]
Saludos

Amigo disculpa la molestia pero me he encontrado con una nueva falla.

Cada vez que hago una solicitud de password baseurl no cambia por el dominio de la página, adjunto te envío la captura

http://prntscr.com/8355me

**Comment by mbassan** [comment]
Se me habrá olvidado hacer un merge del commit que tenía esa función. Estoy
fuera de la oficina por razones personales hasta el 18 de este mes. Al
volver lo reviso - si puedes, por favor crea un issue en Github en
wlox/wlox sobre el tema para que me acuerde.

Gracias y saludos.
