### ISSUE TITLE
recapcha error

### ISSUE THREAD

**Issue by abhijeetjaswal** [wlox/wlox#49]
Deployed Wlox compete package on 2 different server.. one with backstage2, api, cron and auth and another with frontend. all deployed well and i can access the pages. but the problem is when i try to register on frontend, even though the captcha is enter correctly, the page throw error "The verification text does not match the image.Page expired." am i missing something?

**Comment by mbassan** [comment]
First of all, congratulations on getting everything to work from the manual
- it's a bit outdated.

We integrated Google no-captcha into the latest version and we haven't
really tested the fallback to the default captcha after the change.

The easiest solution is probably to sign up to get an api key for Google
recaptcha. You can put it into the app configuration in backstage2.

Let me know if that works.

**Comment by abhijeetjaswal** [comment]
i am using the google api for recaptha but the error persist. do you think to test it shall i keep everything in one server and try.. that ways chances of errors will be less. also DB (the tax.gz file ) is needed for both right? backstage2 and frontend?

**Comment by mbassan** [comment]
Sorry about the delay in responding. I have been away from the office for
personal reasons for a few days.

You can definitely use only one server for testing purposes (multiple
servers are only necessary for a production environment).

The most likely cause of your problem is the session regeneration in
frontend/lib/common.php. Look for a line in that file that says
session_regenerate_id() (or something similar) and comment it out. That
will probably fix your issue.

Best,

WLOX Support

On Wed, Aug 5, 2015 at 12:07 AM, abhijeetjaswal <notifications@github.com>
wrote:

> i am using the google api for recaptha but the error persist. do you think
> to test it shall i keep everything in one server and try.. that ways
> chances of errors will be less. also DB (the tax.gz file ) is needed for
> both right? backstage2 and frontend?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wlox/wlox/issues/49#issuecomment-127855381>.
>



-- 
Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Comment by abhijeetjaswal** [comment]
sorry for my late response.. i tried looking up for session regenerate id in the common.php file but can't find one.

**Comment by mbassan** [comment]
Sorry, it's actually just session_regenerate(). It's near line 40 in
frontend/lib/common.php.

On Wed, Aug 19, 2015 at 2:27 PM, abhijeetjaswal <notifications@github.com>
wrote:

> sorry for my late response.. i tried looking up for session regenerate id
> in the common.php file but can't find one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wlox/wlox/issues/49#issuecomment-132751716>.
>



-- 
Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Comment by scratch87** [comment]
Hi, I have the same problem, I install all in one server but have the same error when try to register or login.
Comment the session_regenerate() don't work for fix this, Some other option?

**Comment by pv16061995** [comment]
Dear Sir, 

i have a issue in registration, i do registration and filled form show success but in database value not save help me.

**Comment by casiumcoin** [comment]
What is your username and email you provided while registering.

**Comment by pv16061995** [comment]
hi, please confirm this project work on localhost or not, and i not got any mail actually after API function can not be hit  registerNew function help me.
