### ISSUE TITLE
Error en el sistema de correo

### ISSUE THREAD

**Issue by imatsu** [wlox/wlox#50]
Al activar 2FA el sistema envía un mensaje el cual no interpola la etiqueta [baseurl] con el dominio del sitio.

http://prntscr.com/8355me

Al solicitar una nueva contraseña también ocurre el mismo problema, e incluso la etiqueta [authcode] tampoco la intercambia o la genera. 

http://prntscr.com/83gn3v

**Comment by mbassan** [comment]
Estuve fuera de la oficina por unos dias. Ya estoy de vuelta y espero tenerlo solucionado pronto.

**Comment by mbassan** [comment]
Acabamos de hacer unas actualizaciones bastante grandes. Me puedes avisar si ya funciona?

**Comment by imatsu** [comment]
Excelente, el fallo que tenía se ha corregido

**Comment by mbassan** [comment]
Perfecto. Solo quiero mencionar entonces que si le funciona bién nuestro producto, nosotros hacemos "deployments" y desarrollo de funcionalidad para WLOX como consultoría - estos tienen como meta habilitar una instancia de WLOX que es seguro y funcional para el mundo real. Saludos.
