### ISSUE TITLE
Troublesome Frontend

### ISSUE THREAD

**Issue by dusupark** [wlox/wlox#52]
Whenever I get access to pages of frontend, I meet one of the followings:

1. Error

The pages display the notices and fatal error.

Notice: Undefined property: object::$default_timezone in /var/www/bitcoin/frontend/lib/common.php on line 82

Notice: date_default_timezone_set(): Timezone ID '' is invalid in /var/www/bitcoin/frontend/lib/common.php on line 82

Notice: Undefined property: object::$default_timezone in /var/www/bitcoin/frontend/lib/common.php on line 83

Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /var/www/bitcoin/frontend/lib/common.php:83 Stack trace: #0 /var/www/bitcoin/frontend/lib/common.php(83): DateTimeZone->__construct('') #1 /var/www/bitcoin/frontend/htdocs/our-security.php(2): include('/var/www/bitcoi...') #2 {main} thrown in /var/www/bitcoin/frontend/lib/common.php on line 83

2. No content

The page title and content are empty.

3. Too slow loading.

The pages load too slowly.

What shall I do? I have installed the recent version on CentOS 7 with PHP Version 5.4.16 MariaDB 5.5.41.

**Comment by mbassan** [comment]
You can contact me at support.wlox on Skype and I will assist you.

On Sun, Aug 30, 2015 at 9:51 PM, dusupark <notifications@github.com> wrote:

> Whenever I get access to pages of frontend, I meet one of the followings:
>
>    1. Error
>
> The pages display the notices and fatal error.
>
> Notice: Undefined property: object::$default_timezone in
> /var/www/bitcoin/frontend/lib/common.php on line 82
>
> Notice: date_default_timezone_set(): Timezone ID '' is invalid in
> /var/www/bitcoin/frontend/lib/common.php on line 82
>
> Notice: Undefined property: object::$default_timezone in
> /var/www/bitcoin/frontend/lib/common.php on line 83
>
> Fatal error: Uncaught exception 'Exception' with message
> 'DateTimeZone::__construct(): Unknown or bad timezone ()' in
> /var/www/bitcoin/frontend/lib/common.php:83 Stack trace: #0
> /var/www/bitcoin/frontend/lib/common.php(83): DateTimeZone->__construct('')
> #1 <https://github.com/wlox/wlox/pull/1>
> /var/www/bitcoin/frontend/htdocs/our-security.php(2):
> include('/var/www/bitcoi...') #2 <https://github.com/wlox/wlox/pull/2>
> {main} thrown in /var/www/bitcoin/frontend/lib/common.php on line 83
>
>    1. No content
>
> The page title and content are empty.
>
>    1. Too slow loading.
>
> The pages load too slowly.
>
> What shall I do? I have installed the recent version on CentOS 7 with PHP
> Version 5.4.16 MariaDB 5.5.41.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wlox/wlox/issues/52>.
>



-- 
Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Comment by dusupark** [comment]
I have solved the problem by setting $CFG->api_url in the frontend's configuration to the IP address instead of the domain name. PHP cURL seems to have some problems with a domain name.

**Comment by mbassan** [comment]
Thank you for reporting. Best regards.

**Comment by nrfzhsf** [comment]
Hi. I am also facing the same problem. How can I fix it? I tried changing the $CFG->api_url already but it didn't work for me.
![screenshot from 2018-01-25 12-35-24](https://user-images.githubusercontent.com/35791632/35371186-78027b88-01cd-11e8-97fb-37e42f77381e.png)
