### ISSUE TITLE
Inicio de sesión

### ISSUE THREAD

**Issue by imatsu** [wlox/wlox#56]
Saludos.

He realizado el proceso de instalación nuevamente y cada vez que una cuenta intenta iniciar sesión el servidor web arroja el siguiente mensaje de error:

[Wed Oct 14 21:13:29.944224 2015] [:error] [pid 13850] [client ::1:46113] PHP Warning:  Single query failed. Retrying... in /var/www/html/wlox/auth/lib/dblib.php on line 109
[Wed Oct 14 21:13:29.944982 2015] [:error] [pid 13850] [client ::1:46113] PHP Fatal error:  Can't execute query<pre>DELETE FROM change_settings WHERE type = 'r' AND site_user = 2</pre>MySQL Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'where clause'Debug: Array\n(\n    [0] => Array\n        (\n            [file] => /var/www/html/wlox/auth/lib/dblib.php\n            [line] => 119\n            [function] => db_log_error\n            [args] => Array\n                (\n                    [0] => PDOException Object\n                        (\n                            [message:protected] => SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'where clause'\n                            [string:Exception:private] => \n                            [code:protected] => 42S22\n                            [file:protected] => /var/www/html/wlox/auth/lib/dblib.php\n                            [line:protected] => 112\n                            [trace:Exception:private] => Array\n                                (\n                                    [0] => Array\n                   in /var/www/html/wlox/auth/lib/dblib.php on line 373

Vale destacar que el proceso de recuperar el password funciona adecuadamente, el enlace es enviado al correo electrónico y al hacer click redirecciona inmediatamente a la sesión del sistema, excepto que cuando cierro sesión debo nuevamente recuperar la contraseña .

**Comment by mbassan** [comment]
Perdona por la respuesta lenta. Por favor ejecuta el siguiente SQL para reemplazar la tabla de **change_settings**:

```
CREATE TABLE IF NOT EXISTS `change_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `request` blob NOT NULL,
  `date` datetime NOT NULL,
  `site_user` int(10) unsigned NOT NULL,
  `type` enum('s','r') NOT NULL DEFAULT 's',
  `email_token` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `site_user` (`site_user`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
```

**Comment by imatsu** [comment]
la falla ya ha sido corregida, muchas gracias por el aporte

**Comment by imatsu** [comment]
Por favor mbassan, comunícate conmigo al correo imatsu@gmail.com
