### ISSUE TITLE
PHP Fatal error:  Can't execute query

### ISSUE THREAD

**Issue by imatsu** [wlox/wlox#57]
El frontend me arroja este error al ingresar a la página principal.

[Thu Oct 15 00:15:28.748820 2015] [:error] [pid 13837] [client ::1:49051] PHP Fatal error:  Can't execute query<pre>SELECT btc_24h AS total_btc_traded FROM status LIMIT 0,1</pre>MySQL Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'btc_24h' in 'field list'Debug: Array\n(\n    [0] => Array\n        (\n            [file] => /var/www/html/wlox/api/lib/dblib.php\n            [line] => 108\n            [function] => db_log_error\n            [args] => Array\n                (\n                    [0] => PDOException Object\n                        (\n                            [message:protected] => SQLSTATE[42S22]: Column not found: 1054 Unknown column 'btc_24h' in 'field list'\n                            [string:Exception:private] => \n                            [code:protected] => 42S22\n                            [file:protected] => /var/www/html/wlox/api/lib/dblib.php\n                            [line:protected] => 72\n                            [trace:Exception:private] => Array\n                                (\n                                    [0] => Array\n                          in /var/www/html/wlox/api/lib/dblib.php on line 378
[Thu Oct 15 00:15:28.749844 2015] [:error] [pid 17577] [client 200.93.120.115:55547] PHP Notice:  Undefined index:  in /var/www/html/wlox/frontend/htdocs/includes/ajax.trades.php on line 44, referer: http://localhost/es/index.php

La tabla total_btc_traded no existe.

mysql> show tables;
+------------------------+
| Tables_in_wlox     |
+------------------------+
| account_types          |
| admin_controls         |
| admin_controls_methods |
| admin_cron             |
| admin_groups           |
| admin_groups_pages     |
| admin_groups_tabs      |
| admin_image_sizes      |
| admin_order            |
| admin_pages            |
| admin_sessions         |
| admin_tabs             |
| admin_users            |
| api_keys               |
| app_configuration      |
| bank_accounts          |
| bitcoin_addresses      |
| bitcoind_log           |
| change_settings        |
| content                |
| content_files          |
| conversions            |
| currencies             |
| current_stats          |
| daily_reports          |
| emails                 |
| fee_schedule           |
| fees                   |
| historical_data        |
| history                |
| history_actions        |
| innodb_lock_monitor    |
| ip_access_log          |
| iso_countries          |
| lang                   |
| monthly_reports        |
| news                   |
| order_log              |
| order_types            |
| orders                 |
| request_descriptions   |
| request_status         |
| request_types          |
| requests               |
| sessions               |
| settings               |
| settings_files         |
| site_users             |
| site_users_access      |
| site_users_balances    |
| site_users_catch       |
| status                 |
| status_escrows         |
| transaction_types      |
| transactions           |
+------------------------+

**Comment by mbassan** [comment]
De nuevo disculpa por la demora en responder. Puedes agregar el campo faltante a la tabla de **status** ejecutando:

```
ALTER TABLE `status` ADD `btc_24h` DOUBLE( 10, 2 ) NOT NULL DEFAULT '0';
```
Saludos.

**Comment by mbassan** [comment]
Hola hermano. Algunas personas que trabajan conmigo me robaron el codigo por una discusion que tuvimos, a partir de revocar mis permisos sobre este organization. Estoy tratando de crear "awarness" de lo que ha pasado. Voy a crear un fork propio.

Esto es un llamado a los usuarios a que ayuden a poder seguir con este proyecto, versus los ladrones corporativos que solo quieren sacar lo que pueden de las personas.

**Comment by imatsu** [comment]
Muchas gracias, la falla ha sido corregida
