### ISSUE TITLE
Please help in setting up WLOX on VPS

### ISSUE THREAD

**Issue by swsDreams** [wlox/wlox#58]
Hello there, I followed the steps mentioned in readme.md, but some how I am not able get the front end running. Please help.

Great script btw..

**Comment by swsDreams** [comment]
When i login to the backend it loges me out if i click on any links.

**Comment by mbassan** [comment]
Hello swsDreams, it sounds like your PHP sessions are not functioning for some reason. Please contact us on Skype at support.wlox for assistance.

In the meantime, check the PHP errors that you receive in your error logs. Look only for errors that say "fatal" or "warning" (you can ignore all errors that say "notice" or "strict").
