### ISSUE TITLE
new install php log

### ISSUE THREAD

**Issue by melmali2828** [wlox/wlox#61]
Hi new install,

![btc](https://cloud.githubusercontent.com/assets/14098096/11121714/0a04998c-8960-11e5-9e9b-4fe866bb539f.JPG)

**Comment by mbassan** [comment]
You need to turn off PHP notifications for backstage2. Please put the
following code in your backstage2/cfg.php:

error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED & ~E_WARNING);
ini_set('display_errors',0);
ini_set('log_errors',1);

On Thu, Nov 12, 2015 at 10:08 AM, melmali2828 <notifications@github.com>
wrote:

> Hi new install,
>
> [image: btc]
> <https://cloud.githubusercontent.com/assets/14098096/11121714/0a04998c-8960-11e5-9e9b-4fe866bb539f.JPG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wlox/wlox/issues/61>.
>



-- 
Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Comment by melmali2828** [comment]
Thanks.
