### ISSUE TITLE
Exception' with message 'DateTimeZone

### ISSUE THREAD

**Issue by melmali2828** [wlox/wlox#62]
Hi,

[Fri Nov 13 15:22:57.545883 2015] [:error] [pid 16986] [client 89.19.6.190:37773] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /var/www/wlox/frontend/lib/common.php:83\nStack trace:\n#0 /var/www/wlox/frontend/lib/common.php(83): DateTimeZone->__construct('')\n#1 /var/www/wlox/frontend/htdocs/index.php(2): include('/var/www/wlox/f...')\n#2 {main}\n  thrown in /var/www/wlox/frontend/lib/common.php on line 83

**Comment by MrDunne** [comment]
You need to set a valid timezone in your database, I would presume. Not sure why they're in the DB but y'know.

**Comment by melmali2828** [comment]
server timezone change,
problem solved.

**Comment by jlubinda** [comment]
having this same problem and database record set to America/Panama. It is still giving the same error. ANyone with solution?

**Comment by directoryio** [comment]
same error

**Comment by jlubinda** [comment]
Found a solution for my problem. The permissions for the folders have to be set to 755. APIs don't work if other permission settings are used.

**Comment by jlubinda** [comment]
Now for another problem. I am not getting any errors but registration is not working.
