### ISSUE TITLE
Page expired.

### ISSUE THREAD

**Issue by nailtaras** [wlox/wlox#64]
Registration knocks at Page expired. what to do

**Comment by mbassan** [comment]
You can comment out line 32 of frontend/lib/common.php.

On Mon, Dec 7, 2015 at 10:16 AM, nailtaras <notifications@github.com> wrote:

> Registration knocks at Page expired. what to do
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wlox/wlox/issues/64>.
>



-- 
Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Comment by nailtaras** [comment]
When you enter a username and password always writes invalid login ...

**Comment by nailtaras** [comment]
You can comment out line 32 of frontend/lib/common.php. --- did not help(((

**Comment by mbassan** [comment]
This is the third time you have submitted the same issue. Closing.
