### ISSUE TITLE
Invalid login information

### ISSUE THREAD

**Issue by nailtaras** [wlox/wlox#65]
When you enter a username and password always writes Invalid login information

**Comment by imatsu** [comment]
I have same issue

**Comment by mbassan** [comment]
Please run the DB update files after 13.1. If the issue persists, please show the PHP error log for the auth library.

**Comment by domgolonka** [comment]
Check that your login.php and verify_token.php are there in the auth/htdocs/ directory and check if you linked them properly in cfg.php. On single servers, you can use symbolic links but need to make sure the whole directory is linked in frontend/htdocs
ex: frontend/htdocs/api/htdocs/api.php

**Comment by mbassan** [comment]
Thanks guys. And as I said before, please use mbassan/wlox. It has a lot
more features,, such as multiple cryptos with multiple wallets.

On Wed, May 25, 2016 at 6:22 PM, domgolonka notifications@github.com
wrote:

> Check that your login.php and verify_token.php are there in the
> auth/htdocs/ directory and check if you linked them properly in cfg.php. On
> single servers, you can use symbolic links but need to make sure the whole
> directory is linked in frontend/htdocs
> ex: frontend/htdocs/api/htdocs/api.php
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/wlox/wlox/issues/65#issuecomment-221736621

## 

Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Comment by ShreyaSarkari** [comment]
thnx ...it workss....!
