### ISSUE TITLE
Can we connect Blocktrail or Bitgo wallets to wlox?

### ISSUE THREAD

**Issue by munawar050** [wlox/wlox#70]
Can we connect Blocktrail or Bitgo wallets to wlox? Or is necessary to run complete bitcoind server.

**Comment by mbassan** [comment]
Unfortunately, at this point, we are only supporting using currency daemons
at this point (such as bitcoind, litecoind, etc). I should mention however
that wlox/wlox is outdated. Please use mbassan/wlox instead. It already
supports multiple cryptocurrencies.

On Tue, Mar 8, 2016 at 2:51 AM, munawar050 notifications@github.com wrote:

> Can we connect Blocktrail or Bitgo wallets to wlox? Or is necessary to run
> complete bitcoind server.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wlox/wlox/issues/70.

## 

Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Comment by munawar050** [comment]
Thank You
