### ISSUE TITLE
Frontend doesn't load 

### ISSUE THREAD

**Issue by domgolonka** [wlox/wlox#73]
When I load the page, it just goes into infinite loop. Doesn't load. When I try to run it with CLI, I get errors:

php -f index.php 
E_NOTICE Error in file �common.php� at line 9: Undefined index: SERVER_NAME
E_WARNING Error in file �common.php� at line 41: Cannot modify header information - headers already sent by (output started at /var/www/bitcoiniacs/frontend/cfg/cfg.php:56)
E_WARNING Error in file �common.php� at line 42: Cannot modify header information - headers already sent by (output started at /var/www/bitcoiniacs/frontend/cfg/cfg.php:56)
E_WARNING Error in file �common.php� at line 43: Cannot modify header information - headers already sent by (output started at /var/www/bitcoiniacs/frontend/cfg/cfg.php:56)
E_WARNING Error in file �session.php� at line 118: Cannot modify header information - headers already sent by (output started at /var/www/bitcoiniacs/frontend/cfg/cfg.php:56)
E_WARNING Error in file �common.php� at line 47: session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/bitcoiniacs/frontend/cfg/cfg.php:56)
E_WARNING Error in file �common.php� at line 47: session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/bitcoiniacs/frontend/cfg/cfg.php:56)
E_WARNING Error in file �session.php� at line 196: Cannot modify header information - headers already sent by (output started at /var/www/bitcoiniacs/frontend/cfg/cfg.php:56)
E_WARNING Error in file �session.php� at line 197: Cannot modify header information - headers already sent by (output started at /var/www/bitcoiniacs/frontend/cfg/cfg.php:56)
E_WARNING Error in file �session.php� at line 199: unlink(/var/lib/php5/sessions/PHPSESSID_213frljcfschf447eep2icu781): No such file or directory
E_WARNING Error in file �session.php� at line 118: Cannot modify header information - headers already sent by (output started at /var/www/bitcoiniacs/frontend/cfg/cfg.php:56)
E_WARNING Error in file �stdlib.php� at line 43: session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/bitcoiniacs/frontend/cfg/cfg.php:56)
E_WARNING Error in file �stdlib.php� at line 43: session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/bitcoiniacs/frontend/cfg/cfg.php:56)
E_WARNING Error in file �stdlib.php� at line 44: session_regenerate_id(): Cannot regenerate session id - headers already sent

**Comment by mbassan** [comment]
Try using mbassan/wlox repositories. They are far ahead of these.

**Comment by domgolonka** [comment]
Thanks I fixed the issue.
