### ISSUE TITLE
Not really an issue, but would be nice to explain..

### ISSUE THREAD

**Issue by ghost** [wlox/wlox#76]
In the frontend, I kept getting this error

![capture](https://cloud.githubusercontent.com/assets/19809270/15879600/4a993776-2ceb-11e6-9ff9-e67c62d7979e.PNG)

Which was because the paths in the cfg for the frontend was incorrect. It would have been nice to know this when setting it up. It made me think that there was something wrong with this revision.

Also.. In the backstage2, I wasn't able to get it to work until I turned error reporting off in the cfg file for it. That would have been nice to know too. 

Anyway, thanks! Going to see what I can get done now that it's installed and working.

Edit: This was with using the mbassen version (https://github.com/mbassan/wlox)

**Comment by mbassan** [comment]
Thanks for the suggestions. We are actually working on some substantial new
features that should be rolled out in the next couple months.

Your issues have definitely come up in the past with other developers and
we will take them into account.

Also, please use mbassan/wlox repos that are more up to date.

Last of all, you can contact us at support.wlox on Skype if you need
assistance.

**Comment by domgolonka** [comment]
Means the API isn't setup properly in frontend's cfg.conf. Make sure it is pointing to the correct address.

**Comment by TestEx1** [comment]
Hello guys, I have tried to run the wlox but I find my self with the same issue, also backstage2 shows me all these notices: 

Notice: Undefined index: print in /opt/lampp/htdocs/backstage2/index.php on line 5

Notice: Undefined index: current_url in /opt/lampp/htdocs/backstage2/index.php on line 6

Notice: Undefined index: current_url in /opt/lampp/htdocs/backstage2/index.php on line 6

Notice: Undefined index: action in /opt/lampp/htdocs/backstage2/index.php on line 7

Notice: Undefined index: bypass in /opt/lampp/htdocs/backstage2/index.php on line 8

Notice: Undefined index: id in /opt/lampp/htdocs/backstage2/index.php on line 10

Notice: Undefined index: target_elem in /opt/lampp/htdocs/backstage2/index.php on line 11

Notice: Undefined variable: _SESSION in /opt/lampp/htdocs/backstage2/index.php on line 15

Notice: Undefined property: object::$default_timezone in /opt/lampp/htdocs/backstage2/index.php on line 18

Notice: date_default_timezone_set(): Timezone ID '' is invalid in /opt/lampp/htdocs/backstage2/index.php on line 18

Fatal error: Class 'String' not found in /opt/lampp/htdocs/backstage2/index.php on line 19

**Comment by ghost** [comment]
Use this repository: https://github.com/mbassan/wlox

Pull from the sub repositorys one at a time. Don't try to do them all at once (may have been fixed, I don't remember) It should work after you do this

**Comment by TestEx1** [comment]
Hi world, I did I pulled them one by one from the last repository to my htdocs directory in xampp, I made sure all the paths in cfg.php including the latest db file but it does not seems to work

**Comment by ghost** [comment]
I didn't test using xampp. I think it might have to do with error reporting. Like, one of the files it calls to throws a warning so it stops working when the warnings are reported. Try turning off error reporting for php.

It's been awhile since I looked at this stuff. I do know the latest version works, but I don't remember everything I did to get it to work.
