### ISSUE TITLE
Asks for login every time I do something on backstage2

### ISSUE THREAD

**Issue by markasoftware** [wlox/wlox#81]
I am using the mbassan fork. Every time I click on something on backstage2, it asks me to login again before completing the action. Usually this is ok, but the problem is that I can't submit anything on app configuration, etc, because form data is not preserved.

**Comment by mbassan** [comment]
The frontend and backstage have conflicting sessions. Open them in
different browsers.

This will not be a problem in a production environment where those
components are on different servers.

**Comment by markasoftware** [comment]
Ok, thank you. Clearing the cookies helps.

**Comment by mbassan** [comment]
You're welcome. Remember to open them in different browsers.
