### ISSUE TITLE
No bitcoind server settings in mbassan fork?

### ISSUE THREAD

**Issue by markasoftware** [wlox/wlox#83]
In the mbassan fork I can not find the bitcoind server settings in backstage2. I have managed to find the settings inside the `wallets` table in the database. I am also wondering why there are two rows in the `wallets` table. Thanks!

**Comment by mbassan** [comment]
Hello,

In backstage2, the wallets table is managed under currencies - > crypto
wallets.

There are multiple rows because wlox supports multiple cryptocurrencies,
each with its own settings.

**Comment by markasoftware** [comment]
thanks. I have some other qeuestions but I'll put htose in different issues.
